routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::middleware(['checkrole:admin'])->group(function (){
    Route::get('/users','Admin\UsersController@index')->name('users');
    Route::post('/users','Admin\UsersController@add')->name('add_user');
    Route::put('/users','Admin\UsersController@edit')->name('edit_user');
    Route::delete('/users','Admin\UsersController@delete')->name('delete_user');
    Route::get('projects/all','Manager\ProjectController@all')->name('all_projects');
    Route::get('project-users/{id}','Admin\UserProjectController@usersToProjects')->name('project_users');
    Route::get('user-projects/{id}','Admin\UserProjectController@projectsToUsers')->name('user_projects');
    Route::post('project-users','Admin\UserProjectController@attach')->name('attach_user');
    Route::delete('project-users','Admin\UserProjectController@detach')->name('detach_user');
    Route::get('event-type','Admin\EventTypeController@index')->name('event_type');
    Route::post('event-type','Admin\EventTypeController@add')->name('add_event_type');
    Route::delete('event-type','Admin\EventTypeController@delete')->name('delete_event_type');
    Route::put('event-type','Admin\EventTypeController@edit')->name('edit_event_type');
});

Route::middleware(['checkrole:manager'])->group(function (){
    Route::resource('projects','Manager\ProjectController');
    Route::get('event','Manager\EventController@index')->name('events');
    Route::post('event','Manager\EventController@add')->name('add_event');
    Route::put('event','Manager\EventController@edit')->name('edit_event');
    Route::delete('event','Manager\EventController@delete')->name('delete_event');
    Route::get('project/{id}/events','Manager\EventController@getProjectEvents')->name('project_events');
});

Route::middleware(['checkrole:user'])->group(function (){
    Route::get('project/{id}/pages','User\PageController@getProjectPages')->name('get_project_pages');
    Route::post('pages','User\PageController@addManual')->name('add_page');
    Route::get('pages','User\PageController@allMyPage')->name('my_page');
});

app/Http/Controllers/Manager/EventController.php
<?php

namespace App\Http\Controllers\Manager;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Event;
use App\Events_type;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Validator;
use Illuminate\Validation\Rule;

class EventController extends Controller
{
    public function index(){
        $user= Auth::user();
        $roles= $user->roles;
        $projects=$user->projects;
        $events=[];
        if($projects){
            foreach($projects as $project){
                //var_dump($project->events);die();
                if($project->events->first()){
                    $events[]=$project->events;
                }
            }
        }
        //var_dump($events);die();
        $events_types= Events_type::all();
        return view('manager.event',array('events_types'=>$events_types,
            'roles'=>$roles,
            'projects'=>$projects,
            'events'=>$events));
    }
    
    public function add(Request $request){
        $data = $request->all();
        $validator = Validator::make($data, [
                    'name' => 'required|string|max:255',
                    'element' => 'required|string|max:255',
                    'url_element'=>'nullable|string',
                    'name_element'=>'nullable|string',
                    'project_id' => 'required|integer',
                    'event_type_id'=>'required|integer',
                ])->validate();
        $project=Auth::user()->projects()->findOrFail($data['project_id']);
        $event_type= Events_type::findOrFail($data['event_type_id']);
        $event= new Event;
        $event->event_name=$data['name'];
        $event->event_element=$data['element'];
        $event->event_url_element=$data['url_element'] ? $data['url_element'] : 'window.location.href';
        $event->event_name_element=$data['name_element'] ? $data['name_element'] : 'title';
        $event->projects()->associate($project);
        $event->events_types()->associate($event_type);
        $event->save();
        return 'success';
    }
    
    public function edit(Request $request){
        $data = $request->all();
        $validator = Validator::make($data, [
                    'id' => 'required|integer',
                    'name' => 'required|string|max:255',
                    'element' => 'required|string|max:255',
                    'url_element'=>'nullable|string',
                    'name_element'=>'nullable|string',
                    'project_id' => 'required|integer',
                    'event_type_id'=>'required|integer',
                ])->validate();
        $project=Auth::user()->projects()->findOrFail($data['project_id']);
        $event_type= Events_type::findOrFail($data['event_type_id']);
        $event= Event::findOrFail($data['id']);
        $event->event_name=$data['name'];
        $event->event_element=$data['element'];
        $event->event_url_element=$data['url_element'] ? $data['url_element'] : 'window.location.href';
        $event->event_name_element=$data['name_element'] ? $data['name_element'] : 'title';
        $event->projects()->associate($project);
        $event->events_types()->associate($event_type);
        $event->save();
        return 'success';
    }
    
    public function delete(Request $request){
        $data = $request->all();
        $validator = Validator::make($data, [
                    'id' => 'required|integer',
                ])->validate();
        $event= Event::findOrFail($data['id']);
        $project= Auth::user()->projects()->find($event->projects_id);
        if(!$project){
            return 'You hasn`t premissions to delete this event!';
        }
        $event->delete();
        return 'success';
    }
    
    public function getProjectEvents(int $id){
        $user= Auth::user();
        $roles= $user->roles;
        $projects=$user->projects;
        $project=$user->projects()->findOrFail($id);
        $events=[];
        if($project){
            $events[]=$project->events;                            
        }
        //var_dump($events);die();
        $events_types= Events_type::all();
        return view('manager.event',array('events_types'=>$events_types,
            'roles'=>$roles,
            'projects'=>$projects,
            'events'=>$events));
    }
}

app/Http/Controllers/Manager/ProjectController.php
<?php

namespace App\Http\Controllers\Manager;

use App\Project;
use App\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Validator;
use Illuminate\Validation\Rule;

class ProjectController extends Controller
{
    
    
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $user = Auth::user();
        $projects = $user->projects()->paginate(20);
        $roles = $user->roles;
        return view('manager.projects',array('projects'=>$projects,'roles'=>$roles));
        
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $roles= Auth::user()->roles;
        return view('manager.addproject', array('roles'=>$roles));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = $request->all();
        $validator = Validator::make($data,['project_name' => 'required|string|max:255'])->validate();
        $project=new Project;
        $project->project_name=$data['project_name'];
        $project->project_key= md5($data['project_name'].'key_generate');
        $project->save();
        $user= Auth::user();
        $user->projects()->attach($project->id);
        $projects = $user->projects()->paginate(20);
        $roles = $user->roles;
        return view('manager.projects',array('projects'=>$projects,'roles'=>$roles));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Project  $project
     * @return \Illuminate\Http\Response
     */
    public function show(Request $request,Project $project)
    {
        $this->checkProjectOwner($project);
        $roles= Auth::user()->roles;
        return view('manager.showproject', array('roles'=>$roles, 'project'=>$project));                
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Project  $project
     * @return \Illuminate\Http\Response
     */
    public function edit(Project $project)
    {
        $this->checkProjectOwner($project);
        $roles= Auth::user()->roles;
        return view('manager.editproject', array('roles'=>$roles,'project'=>$project));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Project  $project
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Project $project)
    {
        $data=$request->all();
        $validator = Validator::make($data, [
                    'project_name'=>'required|string|max:255',
                ])->validate();
        $this->checkProjectOwner($project);
        $project->project_name=$data['project_name'];
        $project->project_key=md5($data['project_name'].'key_generate');
        $project->save();
        return redirect('projects');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Project  $project
     * @return \Illuminate\Http\Response
     */
    public function destroy(Project $project)
    {
        $this->checkProjectOwner($project);
        $project->delete();
        return redirect('projects');
    }
    
    public function all(){
        $projects= Project::paginate(20);
        $roles = Auth::user()->roles;
        return view('manager.projects',array('projects'=>$projects,'roles'=>$roles));   
    }
    
    public function checkProjectOwner(Project $project){
        $user= Auth::user();
        
        if(!$user->hasRole('admin') || !$user->projects->contains($project->id)){
            return redirect('home');
        }
    }
    
}

resources/views/manager/addproject.blade.php
@extends('layouts.app')

@include('layouts.right_nav')
@section('content')
<div class="container">
    <div class="m-t-1">
        <a class="btn-floating btn-large waves-effect waves-light blue right_nav" data-activates="slide-out"><i class="material-icons">menu</i></a>
    </div>
    <div class="row">
        <div class="col m8 offset-m2">

            <div class="m-t-3">
                <form id="add_progect" action="{{ route('projects.store')}}" method="POST">
                    {{ csrf_field() }}
                    <div class="input-field">
                        <input type="text" id="project_name" name="project_name"  required >
                        <label for="project_name" >Название проекта</label>
                    </div>                    
                    <button type="submit" form="add_progect" class="btn waves-effect waves-light green">Добавить</button>
                </form>               
            </div>
            <div class="m-t-1">
                @if ($errors->any())
                <div class="red">
                    <ul>
                        @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
                @endif
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/manager/editproject.blade.php
@extends('layouts.app')

@include('layouts.right_nav')
@section('content')
<div class="container">
    <div class="m-t-1">
        <a class="btn-floating btn-large waves-effect waves-light blue right_nav" data-activates="slide-out"><i class="material-icons">menu</i></a>
    </div>
    <div class="row">
        <div class="col m8 offset-m2">

            <div class="m-t-3">
                <form id="edit_progect" action="{{ route('projects.update',['project'=>$project->id])}}" method="POST">
                    {{ csrf_field() }}
                    {{ method_field('PUT') }}
                    <div class="input-field">
                        <input type="text" id="project_name" name="project_name" value="{{ $project->project_name}}"  required >
                        <label for="project_name" >Название проекта</label>
                    </div>                    
                    <button type="submit" form="edit_progect" class="btn waves-effect waves-light green">Изменить</button>
                </form>               
            </div>
            <div class="m-t-1">
                @if ($errors->any())
                <div class="red">
                    <ul>
                        @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
                @endif
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/manager/event.blade.php
@extends('layouts.app')

@include('layouts.right_nav')
@section('content')
<div class="container">
    <div class="m-t-1">
        <a class="btn-floating btn-large waves-effect waves-light blue right_nav" data-activates="slide-out"><i class="material-icons">menu</i></a>
        <a href="#add-modal" class="btn-floating btn-large waves-effect waves-light green modal-trigger right" ><i class="material-icons">add</i></a>
    </div>
    <div class="row">
        <div class="col m8 offset-m2">
            <h4 class="center-align">Cобытия</h4>
            <div class="m-t-3">
                <ul class="collapsible" data-collapsible="accordion">
                    @forelse($events as $eventarr)
                    @foreach($eventarr as $event)
                    <li>
                        <div class="collapsible-header"><i class="material-icons">event</i>{{$event->event_name}}</div>
                        <div class="collapsible-body">
                            <form class="edit-event" action="{{ route('edit_event')}}" method="POST">
                                {{ csrf_field() }}
                                <input type="hidden" name="id" value="{{$event->id}}">
                                <div class="input-field">
                                    <input type="text" id="name{{$event->id}}" name="name" required value="{{$event->event_name}}">
                                    <label for="name{{$event->id}}" >Имя</label>
                                </div>
                                <div class="input-field">
                                    <input type="text" id="element{{$event->id}}" name="element" required value="{{$event->event_element}}">
                                    <label for="element{{$event->id}}" >Селектор</label>
                                </div>
                                <div class="input-field">
                                    <input type="text" id="url_element{{$event->id}}" name="url_element" value="{{$event->event_url_element}}">
                                    <label for="url_element{{$event->id}}" >Селектор url (по-умолчанию url страницы)</label>
                                </div>
                                <div class="input-field">
                                    <input type="text" id="name_element{{$event->id}}" name="name_element" value="{{$event->event_name_element}}">
                                    <label for="name_element{{$event->id}}" >Селектор названия страницы (по-умолчанию title)</label>
                                </div>
                                <div class="input-field">
                                    <select id="project{{$event->id}}" name="project_id" required>  
                                        <option value="">Выберите проект</option>        
                                        @foreach($projects as $project)
                                        <option value="{{$project->id}}" @if($event->projects_id==$project->id) selected="selected" @endif >{{$project->project_name}}</option>
                                        @endforeach
                                    </select>
                                    <label for="project{{$event->id}}">Проект</label>
                                </div> 
                                <div class="input-field">
                                    <select id="event_type{{$event->id}}" name="event_type_id" required>  
                                        <option value="">Выберите тип события</option>        
                                        @foreach($events_types as $events_type)
                                        <option value="{{$events_type->id}}" @if($event->events_types_id==$events_type->id) selected="selected" @endif >{{$events_type->event_type_name}}</option>
                                        @endforeach
                                    </select>
                                    <label for="event_type{{$event->id}}">Тип события</label>
                                </div> 
                                <button type="submit" class="btn waves-effect black-text waves-light yellow">Изменить</button>
                                <a href="{{ route('delete_event')}}" id="del_{{$event->id}}" class="right-align event_delete tooltipped right" data-position="bottom" data-delay="50" data-id="{{$event->id}}" data-tooltip="Удалить"><i class="delete_Event_type red-text material-icons">clear</i></a>
                            </form>
                        </div>
                    </li>   
                    @endforeach
                    @empty
                    <li></li>
                    @endforelse
                </ul>                
            </div>
        </div>
    </div>
</div>
<div id="add-modal" class="modal">
    <div class="modal-content">
        <form id="add_event" action="{{ route('add_event')}}" method="POST">
            {{ csrf_field() }}
            <div class="input-field">
                <input type="text" id="name" name="name"  required >
                <label for="name" >Имя</label>
            </div>
            <div class="input-field">
                <input type="text" id="element" name="element" required value="">
                <label for="element" >Селектор</label>
            </div>
            <div class="input-field">
                <input type="text" id="url_element" name="url_element" value="">
                <label for="url_element" >Селектор url (по-умолчанию url страницы)</label>
            </div>
            <div class="input-field">
                <input type="text" id="name_element" name="name_element" value="">
                <label for="name_element" >Селектор названия страницы (по-умолчанию title)</label>
            </div>
            <div class="input-field">
                <select id="project" name="project_id" required>  
                    <option value="">Выберите проект</option>        
                    @foreach($projects as $project)
                    <option value="{{$project->id}}" >{{$project->project_name}}</option>
                    @endforeach
                </select>
                <label for="project">Проект</label>
            </div> 
            <div class="input-field">
                <select id="event_type" name="event_type_id" required>  
                    <option value="">Выберите тип события</option>        
                    @foreach($events_types as $events_type)
                    <option value="{{$events_type->id}}" >{{$events_type->event_type_name}}</option>
                    @endforeach
                </select>
                <label for="event_type">Тип события</label>
            </div> 

        </form>
    </div>
    <div class="modal-footer">
        <button type="submit" form="add_event" class="btn waves-effect waves-light green">Добавить</button>
    </div>
</div>
@endsection

resources/views/manager/projects.blade.php
@extends('layouts.app')

@include('layouts.right_nav')
@section('content')
<div class="container">
    <div class="m-t-1">
        <a class="btn-floating btn-large waves-effect waves-light blue right_nav" data-activates="slide-out"><i class="material-icons">menu</i></a>
        <a href="{{ route('projects.create')}}" class="btn-floating btn-large waves-effect waves-light green right" ><i class="material-icons">add</i></a>
    </div>
    <div class="row">
        <div class="col m8 offset-m2">

            <div class="m-t-3">
                <ul class="collection with-header">
                    <li class="collection-header"><h4>Проекты</h4></li>
                    @foreach($projects as $project)
                    <li class="collection-item">
                        <div>{{$project->project_name}}<a href="{{ route('projects.show',['project'=>$project->id])}}" class="secondary-content"><i class="material-icons">send</i></a></div>
                    </li>   
                    @endforeach
                </ul>                
            </div>
        </div>
        <div class="col m10">
            {{ $projects->links() }}
        </div>
    </div>
</div>
@endsection

resources/views/manager/showproject.blade.php
@extends('layouts.app')

@include('layouts.right_nav')
@section('content')
<div class="container">
    <div class="m-t-1">
        <a class="btn-floating btn-large waves-effect waves-light blue right_nav" data-activates="slide-out"><i class="material-icons">menu</i></a>
    </div>
    <div class="row">
        <div class="col m8 offset-m2">

            <div>       
                <ul class="collection with-header">
                    <li class="collection-header"><h4>{{$project->project_name}}</h4></li>
                    <li class="collection-item">
                        <span class="blue-text text-darken-4">Ключ: </span>
                        {{$project->project_key}}
                    </li>
                    <li class="collection-item">
                        <span class="blue-text text-darken-4">Пользователи проекта: </span>
                        <a href="{{ route('project_users',['id'=>$project->id])}}" class="secondary-content"><i class="material-icons">send</i></a>
                    </li>
                    <li class="collection-item">
                        <span class="blue-text text-darken-4">События проекта: </span>
                        <a href="{{ route('project_events',['id'=>$project->id])}}" class="secondary-content"><i class="material-icons">send</i></a>
                    </li>
                    <li class="collection-item">
                        <span class="blue-text text-darken-4">Страницы проекта: </span>
                        <a href="{{ route('get_project_pages',['id'=>$project->id])}}" class="secondary-content"><i class="material-icons">send</i></a>
                    </li>
                </ul>
                <a class="btn waves-effect black-text waves-light yellow" href="{{ route('projects.edit',['project'=>$project->id])}}">Изменить</a>
                <form action="{{ route('projects.destroy',['project'=>$project->id])}}" method="POST">
                    {{ method_field('DELETE') }}
                    {{ csrf_field() }}
                    <button type="submit" class="btn-flat right-align tooltipped right" data-position="bottom" data-delay="50" data-id="{{$project->id}}" data-tooltip="Удалить"><i class="red-text material-icons">clear</i></button>
                </form>                
            </div>
            <div class="m-t-1">
                @if ($errors->any())
                <div class="red">
                    <ul>
                        @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
                @endif
            </div>
        </div>
    </div>
</div>
@endsection