routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::middleware(['checkrole:admin'])->group(function (){
    Route::get('/users','Admin\UsersController@index')->name('users');
    Route::post('/users','Admin\UsersController@add')->name('add_user');
    Route::put('/users','Admin\UsersController@edit')->name('edit_user');
    Route::delete('/users','Admin\UsersController@delete')->name('delete_user');
    Route::get('projects/all','Manager\ProjectController@all')->name('all_projects');
    Route::get('project-users/{id}','Admin\UserProjectController@usersToProjects')->name('project_users');
    Route::get('user-projects/{id}','Admin\UserProjectController@projectsToUsers')->name('user_projects');
    Route::post('project-users','Admin\UserProjectController@attach')->name('attach_user');
    Route::delete('project-users','Admin\UserProjectController@detach')->name('detach_user');
    Route::get('event-type','Admin\EventTypeController@index')->name('event_type');
    Route::post('event-type','Admin\EventTypeController@add')->name('add_event_type');
    Route::delete('event-type','Admin\EventTypeController@delete')->name('delete_event_type');
    Route::put('event-type','Admin\EventTypeController@edit')->name('edit_event_type');
});

Route::middleware(['checkrole:manager'])->group(function (){
    Route::resource('projects','Manager\ProjectController');
    Route::get('event','Manager\EventController@index')->name('events');
    Route::post('event','Manager\EventController@add')->name('add_event');
    Route::put('event','Manager\EventController@edit')->name('edit_event');
    Route::delete('event','Manager\EventController@delete')->name('delete_event');
    Route::get('project/{id}/events','Manager\EventController@getProjectEvents')->name('project_events');
});

Route::middleware(['checkrole:user'])->group(function (){
    Route::get('project/{id}/pages','User\PageController@getProjectPages')->name('get_project_pages');
    Route::post('pages','User\PageController@addManual')->name('add_page');
    Route::get('pages','User\PageController@allMyPage')->name('my_page');
});

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <!-- CSRF Token -->
        <meta name="csrf-token" content="{{ csrf_token() }}">

        <title>{{ config('app.name', 'Laravel') }}</title>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css">
        <!-- Styles -->
        <link href="{{ asset('css/styles.css') }}" rel="stylesheet">
    </head>
    <body>
        <header>
        <ul id="dropdown1" class="dropdown-content">
            <li>
                <a href="{{ route('logout') }}"
                   onclick="event.preventDefault();
                           document.getElementById('logout-form').submit();">
                    Logout
                </a>

                <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                    {{ csrf_field() }}
                </form>
            </li>
        </ul>
        <nav>
            <div class="nav-wrapper green">
                <a href="{{ url('/') }}" class="brand-logo">{{ config('app.name', 'Statistics') }}</a>
                <ul class="right hide-on-med-and-down">
                    <!-- Authentication Links -->
                    @guest
                    <li><a href="{{ route('login') }}">Login</a></li>
                    <li><a href="{{ route('register') }}">Register</a></li>
                    @else
                    <li class="dropdown">
                    <li><a class="dropdown-button" href="#!" data-activates="dropdown1">{{ Auth::user()->name }}<i class="material-icons right">arrow_drop_down</i></a></li>
                    </li>
                    @endguest
                </ul>
            </div>
        </nav>
        </header>
        <main>
        @yield('content')
        </main>
        <footer class="page-footer">
            <div class="footer-copyright">
                <div class="container">
                    <a href="https://grizzly.by">
                        <img class="logo-foot" title="GRIZZLY DIGITAL COMPANY" alt="Логотип GRIZZLY DIGITAL COMPANY" src="https://grizzly.by/assets/template/images/logo.png" float="left" width="30">
                        <p class="foot-name">GRIZZLY.BY</p>
                        <p class="copyrights">2018 All rights reserved</p>
                    </a>
                </div>
            </div>
        </footer>
        
        <!-- Scripts -->
        <script  src="http://code.jquery.com/jquery-3.2.1.min.js"  integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="  crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script>
        <script src="{{ asset('js/site.js') }}"></script>
    </body>
</html>

resources/views/layouts/right_nav.blade.php
<ul id="slide-out" class="side-nav">
    <li>
        <div class="user-view">
            <img src="https://grizzly.by/assets/template/images/logo_black.png">
            <h3 class="red-text">Меню</h3>
        </div>
    </li>
    @foreach ($roles as $role)
        @if($role->name == 'admin')
            <li><a href="{{ route('users') }}"><span>Пользователи</span></a></li>
            <li><a href="{{ route('all_projects') }}">Все проекты</a></li>
            <li><a href="{{ route('event_type') }}"><span >Типы Событий</span></a></li> 
        @endif
        @if($role->name == 'manager')
            <li><a href="{{ route('projects.index') }}"><span >Мои Проекты</span></a></li>
                       
        @endif
        @if($role->name == 'user')
            <li><a href="{{ route('events') }}"><span >События</span></a></li>
            <li><a href="{{ route('my_page') }}"><span >Страницы</span></a></li>
        @endif
    @endforeach
</ul>